[package]
name = "piston_project"
version = "0.1.0"
authors = ["Samzelot <Samzelot@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.66.0"
piston2d-opengl_graphics = "0.73.0"
rand = "0.5.5"

